[tool.ruff]
# Set the maximum line length to 79.
line-length = 79

[tool.ruff.lint]
extend-select = ["E501"]

[tool.pytest.ini_options]
markers =[
    "slow: mark test as slow."
]
[tool.coverage.run]
omit = ["*.spec"]