[tox]
envlist = py3{10-14}

[testenv]
dependency_groups = test
commands = pytest --basetemp={envtmpdir} {posargs}


[testenv:mypy]
dependency_groups = type-checking
skip_install = True
commands =
    mypy -p package_speedwagon
